2024-12-12 13:26:06,378 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\MyProjectPycharm\Urban_University\module_12\tests_12_4.py", line 73, in test_run
    self.second = Runner(5, 5)
                  ^^^^^^^^^^^^
  File "D:\MyProjectPycharm\Urban_University\module_12\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-12 13:26:06,382 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\MyProjectPycharm\Urban_University\module_12\tests_12_4.py", line 61, in test_walk
    self.first = Runner('Вася', -5)
                 ^^^^^^^^^^^^^^^^^^
  File "D:\MyProjectPycharm\Urban_University\module_12\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
